### ISSUE TITLE
SyntaxError: An invalid or illegal string was specified in Firefox

### ISSUE THREAD

**Issue by warpech** [Starcounter/DevTools#16]
Switching to "Imports" tab breaks webcomponents.js polyfill with the error message:

```
SyntaxError: An invalid or illegal string was specified
```

(tested with Polymer 0.5.5)

**Comment by miyconst** [comment]
For me the Launcher & People app does not work under FF at all.
And the exception above fires after Esc + `, not after Imports tab selected.

**Comment by warpech** [comment]
Closing as not reproducible anymore
