### ISSUE TITLE
Detect Custom Elements that are unimported or imported twice

### ISSUE THREAD

**Issue by warpech** [Starcounter/DevTools#5]
InvoiceDemo declared an instance of `<puppet-js>`, but the imported link was changed in the meantime to `puppet-client.html`. Therefore, `<puppet-js>` is not resolved. Browser ignores this silently without an error.

"Imports" tab (or a new tab?) should notify the developer about using unimported Custom Elements.

**Comment by warpech** [comment]
Closing as hard to develop

**Comment by warpech** [comment]
Reopening, since I think this is doable.

If DevTools overloads `customElements.define`, it can actually detect custom elements definitions. This will tell us if some element is not loaded at all or is loaded twice.

**Comment by alshakero** [comment]
So we should keep track of defined elements + compare them against DOM elements? When do we scan the DOM?

**Comment by warpech** [comment]
> So we should keep track of defined elements + compare them against DOM elements? 

Yes

> When do we scan the DOM?

When the [Health check](https://github.com/Starcounter/RebelsLounge/issues/222#issuecomment-348360498) tab in DevTools is opened. That tab might have a button that re-runs the check.

**Comment by alshakero** [comment]
Wow, thanks to `customElements.get` we don't need to keep track of definitions! 

Check this:

https://jsbin.com/vecejux/1/edit?html,js,console,output

**Comment by warpech** [comment]
Great! Please note that it is categorized as "later" on the project board.

**Comment by alshakero** [comment]
This is now on master! It should be released once Mihai confirms https://github.com/Starcounter/DevTools/issues/71 is fixed.

**Comment by alshakero** [comment]
Haha Mihai confirmed now! I'll release now.

**Comment by alshakero** [comment]
Released in https://github.com/Starcounter/DevTools/releases/tag/3.2.0
