### ISSUE TITLE
View-model tree shows empty object after page reload

### ISSUE THREAD

**Issue by miyconst** [Starcounter/DevTools#63]
Steps to reproduce:

- Navigate to `http://inside.starcounter.com/`.
- Open SDA in a popup.
- Reload page.

![image](https://user-images.githubusercontent.com/6435556/33829532-f901b922-de70-11e7-89f7-114f1fd4dd4d.png)

**Comment by alshakero** [comment]
Fixed in https://github.com/Starcounter/DevTools/commit/8947349f8cf5625648a575fb3581f73c54df7b97

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/DevTools/releases/tag/3.1.0
