### ISSUE TITLE
Becomes very slow sometimes (probably due to bigger view-models)

### ISSUE THREAD

**Issue by alshakero** [Starcounter/DevTools#65]

**Comment by warpech** [comment]
This was observed in `Flex....` project in Starcounter. @habib535 might know how to reproduce. I think I saw it on the person's page.

**Comment by alshakero** [comment]
More details would be appreciated. I couldn't get it any slower than 500ms.

**Comment by habib535** [comment]
@alshakero can you access http://bio-concept-vm/Bioconcept/Customers ? might require vpn to be connected. Select any customer and try opening the starcounter dev tool.

**Comment by alshakero** [comment]
Thanks a lot! Yes I could using VPN.

**Comment by chrhol** [comment]
Any updates on this issue? Heads also got this problem.

**Comment by alshakero** [comment]
@chrhol Not yet but I'll focus on it.

**Comment by alshakero** [comment]
Fixed in https://github.com/Starcounter/DevTools/commit/e6c4cc3df5592d128b6e5f1a16ee075f241dc4d6. Poor Vue was filtering through 14.5K duplicated imports.

Released 3.1.0 for FF and Chrome. You should see it in your browser automatically by the morning. If the issue presists please make sure you're running 3.1.0, if it still persists even in 3.1.0 feel free to reopen this issue.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/DevTools/releases/tag/3.1.0

**Comment by alshakero** [comment]
@atifwaqar reported this issue again. His app has 129919 imports and I think we should create an async way with progress bar so solve this one and for all even if the app had 1M imports.

**Comment by warpech** [comment]
For me this means the only way is to dedupe. 

How does `bower list` deal with that? Does it print 129919 lines?

**Comment by alshakero** [comment]
No of course not. But they don't have an option to show dupes at all. Can we remove this feature? It's half of the problem.

**Comment by warpech** [comment]
Yes, let's just remove the dupes.

**Comment by alshakero** [comment]
PR in https://github.com/Starcounter/DevTools/pull/75

**Comment by alshakero** [comment]
Released 3.3.0 for FF and Chrome. It should be in users browsers in around 2 hours.
