### ISSUE TITLE
Print imports tree in console or add a file download feature

### ISSUE THREAD

**Issue by alshakero** [Starcounter/DevTools#67]
Some apps import 20K imports, making listing them very slow in the UI. Consider printing the whole tree in console (stylized) or create a file download feature that creates something like `npm ls` or `bower list`.

// cc @tomalec

**Comment by tomalec** [comment]
I like the approach of file download, if we will make it explicitly on-demand, so user have to click to ask for the duplicates, it could take longer.

**Comment by warpech** [comment]
Having a file download is bad for UX because it changes 1-second action into a 10-second action.

Can we have just an unstyled `<pre>` with raw imports tree output? It should accept any reasonable amount of text.

**Comment by alshakero** [comment]
Closing as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/DevTools/releases/tag/3.1.2
- uploaded for Chrome and Mozilla stores.
