### ISSUE TITLE
Change Starcounter debug aid to Starcounter DevTools

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/DevTools#69]
Starcounter DevTools is still called Starcounter debug aid in some places. This should probably be changed. See screenshot:

![capture](https://user-images.githubusercontent.com/19392292/35031595-e7d3c248-fb63-11e7-959e-ef203ef64547.PNG)

**Comment by warpech** [comment]
Closing as done in https://github.com/Starcounter/DevTools/pull/70. Thanks for reporting

**Comment by alshakero** [comment]
Released in https://github.com/Starcounter/DevTools/releases/tag/3.2.1
