### ISSUE TITLE
Page freezes at restart

### ISSUE THREAD

**Issue by Mihaiii** [Starcounter/DevTools#71]
I tried with version 3.1.1 from Chrome Web Store and version 3.1.2 (latest release) from local.

This was also mentioned here: https://github.com/Starcounter/DevTools/issues/51#issuecomment-346888411

Steps within gif:

![freeze](https://user-images.githubusercontent.com/8951553/35215730-7f7faa58-ff65-11e7-9584-0140f0a4ea4a.gif)

@alshakero Could you please have a look?

**Comment by alshakero** [comment]
Hi @Mihaiii! I did a major chanegs to DevTools and I need your help a little. I fixed this issue and enhanced many things. Could you check if that's true by adding the extension from this zip
[extension.zip](https://github.com/Starcounter/DevTools/files/1656001/extension.zip)

**Comment by Mihaiii** [comment]
🥇 
This issue is solved! :)
Thank you!

**Comment by alshakero** [comment]
Thank you so much!

**Comment by alshakero** [comment]
Fix released in https://github.com/Starcounter/DevTools/releases/tag/3.2.0
