### ISSUE TITLE
Register a dummy custom element `puppet-client` that throws an error on construction

### ISSUE THREAD

**Issue by alshakero** [Starcounter/DevTools#74]
We dropped support for `puppet-client` element and now there is no proper error if you still use it by mistake. This is obviously isn't the best UX.

I think creating a dummy error-throwing element in DevTools would help our users big time.

```js
customElements.define('puppet-client', function() {
  const elements = document.querySelectorAll('puppet-client');
  const paths = [];
  for(let el of elements) {
    const path = [el.localName];
    while((el = el.parentNode)) {
      el.localName && path.push(el.localName);
    }
    paths.push(path.reverse().join(' > '));
  }
  const allPaths = paths.join('\n\t\t');
  throw new TypeError(`puppet-client is no longer a valid Starcounter element. Please use palindrom-client instead\n\n\tFound element${paths.length > 1 ? 's' :''}:\n\t\t${allPaths}\n`);
})
```
Whould yield: 
![image](https://user-images.githubusercontent.com/17054134/35478109-2719deb4-03d5-11e8-9264-836f170893c6.png)

See: https://jsbin.com/xoqerac/3/edit?html,js,console

WDYT @tomalec @warpech

**Comment by warpech** [comment]
Thanks for suggesting, but I think it is not needed. The part in our roadmap is titled "Cleanup the legacy code" for a reason of having no legacy stuff in 2.4.

Did you witness a case when it would be useful?

**Comment by alshakero** [comment]
I don't know if it's needed tbh, I just hate silent failures a lot.

**Comment by warpech** [comment]
At least this would be an immediate silent failure :)

Closing this because it is a rare occasion for us to skip having to do a backward compatibility task.

But thanks a lot for proposing such things!
