### ISSUE TITLE
Misleading "offered by" link on Chrome App Store

### ISSUE THREAD

**Issue by mtornwall** [Starcounter/DevTools#80]
Should say "Offered by Starcounter". Instead says "Offered by browser-extensions".

![offeredby](https://user-images.githubusercontent.com/1321973/36378179-17c10bfc-157a-11e8-8ea3-5dda992cfbda.png)

**Comment by alshakero** [comment]
Fixed https://chrome.google.com/webstore/detail/starcounter-devtools/mpchkilmmalfopikamgellgdgoidhmnh
