### ISSUE TITLE
⏰ Overlay doesn't work as should

### ISSUE THREAD

**Issue by Mihaiii** [Starcounter/DevTools#82]
Please see the gif for steps (I try to expand "WebsiteProvider_0", but it doesn't work and I try to select "Text" option, but it doesn't work).
The version is 3.3.1 (current latest on Chrome Web Store).

![bug_sda](https://user-images.githubusercontent.com/8951553/36665639-6a5a01f2-1ae8-11e8-969f-49a7bf54d3b4.gif)

Haven't tried with another app because I would have to install another version of SC first. 
@alshakero , if you have a "normal" SC 2.4 version already installed, please try it first with another app.

**Comment by Mihaiii** [comment]
I tried it now on `http://inside.starcounter.com/people` - same problem so it's not app related.

**Comment by alshakero** [comment]
Thank you for reporting! I managed to repro it. Will look into it.

**Comment by Mihaiii** [comment]
> same problem so it's not app related.

I had an actual look on it and it kinda is app related in a sense that the Search app sends a patch whenever a click is made.

But a closely related issue here is that the whole tree is reevaluated whenever a patch is sent from the client, which would refresh the path that the user currently sees on "View-Model" tab with "tree" option.

Since the refresh of the whole tree whenever a patch is sent from the client is not really going to change very soon and also because probably the code of DevTools should be changed for this (I don't know), the current issue might not be as urgent as the initial post suggests

Here is an example using the popup mode (and not the overlay mode). Please note how the path isn't updated, even though nothing is expanded anymore:

![devtools](https://user-images.githubusercontent.com/8951553/38590830-e9bfe67e-3d33-11e8-823e-479b13751992.gif)
:

Search app branch `master-2.4` will be upgraded with [this commit](https://github.com/Starcounter/Search/pull/33/commits/cade55d1811a0ebe31a99e6e0f4a796489af1fa8) or [this commit](https://github.com/Starcounter/Search/commit/0bf85bdbd7b9a21a0bc0eddf70ac191188250b61) in order to avoid the problem shown in the initial post.

**Comment by warpech** [comment]
Solved in the release https://github.com/Starcounter/DevTools/releases/tag/3.5.0 by removing of the overlay mode. Now there is only the popup mode.
