### ISSUE TITLE
Crashes ocassionally 

### ISSUE THREAD

**Issue by alshakero** [Starcounter/DevTools#83]
I don't have much details and would really appreciate any input. 

Does it crash after you leave it open for a very long time? Or randomly?

Any reproducing steps would be nice.

/cc @malx122

**Comment by warpech** [comment]
It was reported to me by few people that DevTools crashes or freezes when it is open for a long time. If I understand correctly, this entails that many Starcounter sessions go through it before it starts to freeze. Maybe there's some memory leak.

**Comment by alshakero** [comment]
There is a memory leak by design. It collects every patch throughout the session. I'll make it collect top 50. WDYT?

**Comment by warpech** [comment]
Possibly related: https://github.com/Starcounter/DevTools/issues/85
