### ISSUE TITLE
Opener window management

### ISSUE THREAD

**Issue by warpech** [Starcounter/DevTools#85]
What I find missing in Starcounter DevTools is proper lifecycle handling of `window.opener`. What happens when the opener tab is closed? The DevTools remains open. Is Palindrom session properly detached at this point?

I think there should be some information like: 

> This is Starcounter DevTools opened by the tab `http://localhost:8080/UniformDocs/FileUpload` <kbd>Focus tab</kbd>

The URL should be the current URL of the opener tab.

Clicking on the <kbd>Focus tab</kbd> button should focus the opener.

When that tab gets closed, the <kbd>Focus tab</kbd> button should become permanently disabled. After that button display text `That tab is closed now.`

**Comment by alshakero** [comment]
I agree with the <kbd>Focus tab</kbd> idea. But I think the devtools should be closed when the tab is closed or navigated away. WDYT?

**Comment by tomalec** [comment]
I upvote the <kbd>Focus tab</kbd> + closing when opener closed or navigated away

**Comment by alshakero** [comment]
Closing as done in #97
