### ISSUE TITLE
Remove "overlay mode" from DevTools?

### ISSUE THREAD

**Issue by warpech** [Starcounter/DevTools#87]
I think that for maintainability reasons, there should be no overlay mode in Starcounter DevTools. Vue or React DevTools only have one mode.

This would let us avoid problems like https://github.com/Starcounter/DevTools/issues/82

Can we please have a popular vote from the extension users perspective?

Make a reaction of THUMBS UP to remove "overlay mode" or THUMBS DOWN to keep it.

cc @Starcounter/webplatformteam, @Starcounter/sc-apps, @malx122, @erikvk

**Comment by PatrykSzwer** [comment]
With popup feature, I completely stopped using overlay mode. It outclasses overlay in every term of usability. We should just have the popup showing up immediately after clicking the tool icon.
